---
title: Nuvane Health
baseline: Your fitness assistance
description: All about Diet and Fitness.
keywords: Diet, Health and fitness
author: Arnaud Ligny
baseurl: "/"
canonicalurl: false
theme: hyde
date:
  format: j F Y
  timezone: Europe/Paris
output:
  formats:
  - name: netlify_redirects
    mediatype: text/plain
    extension: ''
virtualpages:
- path: admin
  title: Content Manager (Netlify CMS)
  layout: admin/index
  output: html
- path: _redirects
  output: netlify_redirects
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
postprocess:
  enabled: true
